/******************************************************************************
*
*    Copyright WIS Technologies (c) (2003)
*    All Rights Reserved
*
*******************************************************************************
*
*    FILE: 
*        config_error.h
*
*    DESCRIPTION:
*        
*   
*
*    AUTHOR:
*	
*
*    <SOURCE CONTROL TAGS TBD>
*
******************************************************************************/

#ifndef __CONFIG_ERROR_H__
#define __CONFIG_ERROR_H__

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
// confiuration errors
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

enum CONFIG_ERROR
{
	ERROR_NONE = 0,
	ERROR_FILE_NOT_EXIST,
	ERROR_FILE_CORRUPTED,
	ERROR_VERSION,

	ERROR_CONFIG_INCOMPLETE,
	ERROR_CONFIG_TOO_MUCH_ENTRY,
	ERROR_CONFIG_INVALID_RESOLUTION,
	ERROR_CONFIG_SEQUENCE_MODE,
	ERROR_CONFIG_GOP_SIZE,
	ERROR_CONFIG_GOP_MODE,
	ERROR_CONFIG_DVD_COMPLIANT,
	ERROR_CONFIG_ASPECT_RATIO,
	ERROR_CONFIG_MPEG4_FOURCC,
	ERROR_CONFIG_INVERSE_TELECINE,
	ERROR_CONFIG_INTERLACE_CODING,
	ERROR_CONFIG_DEINTERLACE_MODE,
	ERROR_CONFIG_BITRATE_CONTROL,
	ERROR_CONFIG_IIP_ENABLE,
	ERROR_CONFIG_DROP_FRAME,
	ERROR_CONFIG_TV_STANDARD_RES,
	ERROR_CONFIG_TV_STANDARD_FPS,
	ERROR_CONFIG_FILTER_PARAMETERS,
	ERROR_CONFIG_SEARCH_RANGE,
	ERROR_CONFIG_STREAM_HEADER,
	ERROR_CONFIG_VIDEO_CAPABILITY,

	ERROR_CONFIGKS_INCOMPATIBLE_EXTENSION,

	ERROR_UNKNOWN_STREAM_PARAMETER,
	ERROR_UNKNOWN_BITRATE_PARAMETER,
	ERROR_UNKNOWN_RESOLUTION_PARAMETER,
	ERROR_UNKNOWN_FRAMERATE_PARAMETER,

	ERROR_HARDWARE_LIMITATION,
	ERROR_FIRMWARE_LIMITATION,
	ERROR_DRIVER_LIMITATION,
	ERROR_SOFTWARE_LIMITATION,

	ERROR_SENSOR_SETTING,
	ERROR_STREAM_SETTING,
	ERROR_AUDIO_SETTING,

	ERROR_PARSER_TOO_MUCH_CONFIG,
	ERROR_PARSER_INVALID_ENTRY_NAME,
	ERROR_PARSER_DUPLICATED_ENTRY_NAME,
	ERROR_PARSER_INVALID_SYMBOL,
	ERROR_PARSER_INVALID_TVSTANDARD,

	ERROR_PARSER_STREAM_PARAMETER_MISSING,
	ERROR_PARSER_INVALID_COMPRESS_MODE,
	ERROR_PARSER_INVALID_SEQUENCE_MODE,
	ERROR_PARSER_INVALID_MPEG4_MODE,
	ERROR_PARSER_INVALID_DVD_COMPLIANT,
	ERROR_PARSER_INVALID_DEINTERLACE_MODE,
	ERROR_PARSER_INVALID_SEARCH_RANGE,
	ERROR_PARSER_INVALID_ASPECT_RATIO,

	ERROR_PARSER_FRAMERATE_PARAMETER_MISSING,

	ERROR_PARSER_BITRATE_PARAMETER_MISSING,
	ERROR_PARSER_BITRATE_TARGET_BITRATE,
	ERROR_PARSER_BITRATE_PEAK_BITRATE,
	ERROR_PARSER_BITRATE_CONVERGE_SPEED,
	ERROR_PARSER_BITRATE_LAMBDA,
	ERROR_PARSER_BITRATE_Q,

	ERROR_PARSER_RESOLUTION_PARAMETER_MISSING,
	ERROR_PARSER_RESOLUTION_BITRATE_RANGE,
	ERROR_PARSER_RESOLUTION_SCALE_OFFSET,

	ERROR_OUT_OF_MEMORY,
	ERROR_OTHERS,
	ERROR_UNKNOWN
};

#ifdef __cplusplus
extern "C" {
#endif

extern char* config_error_message[];

#ifdef __cplusplus
}
#endif

#endif

/****************************** end of config_error.h ************************/
